//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 01:13:09 PM MSK 
//


package ru.namazov.pas.talon.controller.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.namazov.pas.talon.controller.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.namazov.pas.talon.controller.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetScheduleRequest }
     * 
     */
    public GetScheduleRequest createGetScheduleRequest() {
        return new GetScheduleRequest();
    }

    /**
     * Create an instance of {@link ScheduleXML }
     * 
     */
    public ScheduleXML createScheduleXML() {
        return new ScheduleXML();
    }

    /**
     * Create an instance of {@link GetScheduleResponse }
     * 
     */
    public GetScheduleResponse createGetScheduleResponse() {
        return new GetScheduleResponse();
    }

    /**
     * Create an instance of {@link TalonXML }
     * 
     */
    public TalonXML createTalonXML() {
        return new TalonXML();
    }

    /**
     * Create an instance of {@link PatientXML }
     * 
     */
    public PatientXML createPatientXML() {
        return new PatientXML();
    }

    /**
     * Create an instance of {@link DoctorXML }
     * 
     */
    public DoctorXML createDoctorXML() {
        return new DoctorXML();
    }

}
